version: '3.9'

services:
  etcd1:
    image: ${ETCD_IMG}
    container_name: etcd1
    hostname: etcd1
    restart: always
    ports:
      - "${ETCD1_PORT}:2379"
      - "${ETCD1_80_PORT}:2380"
    volumes:
      - "${ETCD1_DATA}:/etcd/data"
    environment:
      ETCD_NAME: "etcd1"                                      # etcd集群中的节点名
      ETCD_DATA_DIR: "/etcd/data"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd1:2379"         # 建议使用的客户端通信url, 用于etcd代理或etcd成员通信
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd1:2380"   # 建议用于节点间通信的url
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"          # 监听用于客户端通信的url
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"            # 监听用于节点之间的通信url
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"              # 设置该值后， 集群将生成唯一ID，并为每个节点生成唯一ID
      ETCD_INITIAL_CLUSTER_STATE: "new"                       # 新建集群的标志
      ETCD_ROOT_PASSWORD: ${ETCD_ROOT_PASSWORD}
      ETCD_ACTIVE_ENDPOINTS: "http://0.0.0.0:2380" # 显式指定ETCD_ACTIVE_ENDPOINTS环境变量为集群中可用的peer_endpoint即可。
    depends_on:
      - etcd2
      - etcd3
  etcd2:
    image: ${ETCD_IMG}
    container_name: etcd2
    hostname: etcd2
    restart: always
    ports:
      - "${ETCD2_PORT}:2379"
      - "${ETCD2_80_PORT}:2380"
    volumes:
      - "${ETCD2_DATA}:/etcd/data"
    environment:
      ETCD_NAME: "etcd2"
      ETCD_DATA_DIR: "/etcd/data"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd2:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd2:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_ROOT_PASSWORD: ${ETCD_ROOT_PASSWORD}
    depends_on:
      - etcd3
  etcd3:
    image: ${ETCD_IMG}
    container_name: etcd3
    hostname: etcd3
    restart: always
    ports:
      - "${ETCD3_PORT}:2379"
      - "${ETCD3_80_PORT}:2380"
    volumes:
      - "${ETCD3_DATA}:/etcd/data"
    environment:
      ETCD_NAME: "etcd3"
      ETCD_DATA_DIR: "/etcd/data"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd3:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd3:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_ROOT_PASSWORD: ${ETCD_ROOT_PASSWORD}
    networks:
      - rat-race

networks:
  rat-race:
    driver: bridge
    name: rat-race