version: "3.9"
services:
  redis:
    image: ${REDIS_IMG}
    container_name: rat-race-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${REDIS_CONF}:/etc/redis.conf"
      - "${REDIS_DATA}:/data"
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - rat-race
    environment:
      TZ: ${TZ}

networks:
  rat-race:
    driver: bridge
    name: rat-race
