Service:
  Host: 0.0.0.0
  RunMode: dev

Grpc:
  Port: 8082
  TransDataSize: 10
  TransDataUnit: GB

Gateway:
  Port: 8080

Mariadb:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Pass: 123456
  DbName: rat-race


