Server:
  Name: rat-race
  LogLevel: debug
  GrpcConf:
    Port: 9090
  GatewayConf:
    Port: 8080

Etcd:
  Endpoints:
    - 127.0.0.1:32179
    - 127.0.0.1:32279
    - 127.0.0.1:32379
  Username: root
  Password: 123456
  DialTimeOut: 5

Log:
  Filename: ./log/error.log
  MaxSize: 128
  MaxAges: 30
  MaxBackus: 300
  Compress: false
  LocalTime: false
  Console: true

#Service:
#  Host: 0.0.0.0
#  RunMode: dev
#  Name: rat-race
#
#Grpc:
#  Port: 8082
#  TransDataSize: 10
#  TransDataUnit: GB
#
#Gateway:
#  Port: 8080
#
#Mariadb:
#  Host: 127.0.0.1
#  Port: 3306
#  User: root
#  Pass: 123456
#  DbName: rat-race
#  MaxOpenConn: 30
#  MaxIdleConn: 10
#  ConnMaxLifeTime: 60
#
#Logger:
#  MaxSize: 150
#  MaxAge: 30
#  MaxBackups: 300
#  Compress: true
#  LocalTime: true
#  IsConsole: true
#  FileName: ./logs/error.log
#  Level: info
#
#Redis:
#  Host: 127.0.0.1
#  Port: 6379
#  Pass: 123456 # requirepass
#  Db: 0
#  MinIdleConns: 5 # 最小空闲连接数
#  PoolSize: 10 # 连接池个数
#
#Captcha:
#  Type: math # audio 音频, string 字符串 + 数字, math 算术运算
#  Height: 50
#  Width: 100
#  NoiseCount: 0
#  Length: 4
#  ExpireTime: 10
